### ISSUE TITLE
"Unknown type name UIImage" in xcode 6 when implementing model

### ISSUE THREAD

**Issue by james3burke** [Citrrus/MBContactPicker#87]
Hi, I get the error "Unknown type name UIImage" for MBContactModel.h when I try to implement my own contact model - I guess because it doesn't import UIKit. This is in xcode 6.1.1 and cocoapods is importing MBContactPicker 0.1.4.

Thanks.

**Comment by MattCBowman** [comment]
Hey @james3burke - would it fix your situation if we imported UIKit into the MBContactModel?

**Comment by james3burke** [comment]
Yeah, I think that's all it needs.

**Comment by MattCBowman** [comment]
The latest version, 0.1.5, which should be available now. It references UIKit as a framework dependency in the podspec.

**Comment by james3burke** [comment]
Still got the same issue with 0.1.5
