### ISSUE TITLE
Delegate method badly named and not present in protocol 

### ISSUE THREAD

**Issue by npahucki** [Citrrus/MBContactPicker#89]
The method `-(void) contactcollectionView:(MBContactCollectionView *)contactCollectionView didEnterCustomContact:(NSString*)text ` can be called on the `MBContactPickerDelegate`. However, this method suffers from two problems: 

1) It's not named consistently with the other methods, it should be: `-(void) contactCollectionView:(MBContactCollectionView *)contactCollectionView didEnterCustomContact:(NSString*)text`
2) This method is NOT declared in the `MBContactPickerDelegate` protocol, but there is a completely unused method called `- (void)contactPicker:(MBContactPicker*)contactPicker didEnterCustomText:(NSString*)text;`. I Imagine this this method was meant to have the same function as the misnamed method, but some how got overlooked. 

Both super easy fixes. If I get a few moments later today I'll send a pull request.

**Comment by MattCBowman** [comment]
Hey @npahucki - I think you found the result of a bad merge :flushed:. I'll get your updates integrated once you submit. Thanks!

**Comment by npahucki** [comment]
I addressed this in pull request #90.
